### ISSUE TITLE
Error in _runproc prevents it from overwriting Exif

### ISSUE THREAD

**Issue by mdelolmo** [EdLeafe/pyexif#19]
This is the stacktrace:
```
Traceback (most recent call last):
  File "/Users/myuser/projects/album/main.py", line 23, in set_date
    metadata.setTag('DateTimeOriginal', datestamp)
  File "/Users/manuelo/projects/album/venv/lib/python3.9/site-packages/pyexif/pyexif.py", line 246, in setTag
    out = _runproc(cmd, self.photo)
  File "/Users/manuelo/projects/album/venv/lib/python3.9/site-packages/pyexif/pyexif.py", line 32, in _runproc
    if (err.startswith("Warning: Bad ExifIFD directory")
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
The actual error reads something like
`b'Warning: [minor] Ignored empty rdf:Bag list for Iptc4xmpExt:LocationCreated - picture.jpg\n'`

**Comment by EdLeafe** [comment]
Can you try again with the current release (1.0.0)? This should be fixed.

**Comment by mdelolmo** [comment]
Thanks for fixing!
